plugins {
    id 'java'
    id "application"
}

group 'fr.bamandine'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.github.javafaker:javafaker:1.0.2'
}

ext {
   javaMainClass = "src.main.java.fr.bamandine.main.Main"
}

application {
    mainClassName = javaMainClass
}